### SIGNUP
POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "email" : "teste@teste2.com",
  "name" : "teste2",
  "password" : "teste2",
  "role" : "admin"
}

### LOGIN

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email" : "teste@teste.com",
  "password" : "teste"
}

### Create Band

POST http://localhost:3000/band/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwYzQzNzNjLWQyM2UtNGM1NC05YjA4LWJiZWQ2MWQ0MWE3NCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTY5MTIxNSwiZXhwIjoxNjY5Nzc3NjE1fQ.GQJq8cUkt7VoxYIiGLslgimGQ_kab6ZX1AZEmzvfdZ4

{
  "name" : "Chiclete com Banana",
  "music_genre" : "Axé",
  "responsible" : "Bell Marques"
}

### SEARCH BAND

GET http://localhost:3000/band/search?name=chi


### CREATE SHOW

POST http://localhost:3000/show/create
Content-Type: application/json

{
  "weekDay": "Sabado",
  "startTime": 9,
  "endTime": 22,
  "bandId": "a0b88327-2377-4403-a83f-b78879808ca5"
}

### GET SHOWS

GET http://localhost:3000/show?weekDay=SABADO
